### ISSUE TITLE
IP Forwarding

### ISSUE THREAD

**Issue by admiraltidebringer** [pouramin/Iran-vpn#5]
ممنون از آموزش، به خوبی کار می کنه. دو تا سوال داشتم ازتون، ممنون می شم جواب بدید. اول اینکه من تا حدودی با لینوکس آشنایی دارم، از سه تا دستور آیپی سر در نیاورم، منبعی هست که توضیح داده باشه و بشه یاد گرفت؟
و سوال دوم اینکه آیا میشه برای دو سرور اروپا، از یه سرور ایران استفاده کرد؟ یا باید رابطه یک به یک باشد؟

**Comment by pouramin** [comment]
درود؛
برای هر بخشی توی لینوکس میتونید از man  توی خود لینوکس استفاده کنید، مشابه help توی خط فرمان ویندوز عمل میکنه.
توی بخش آی پی فوروادینگ میگیم هرچی آی پی از پورت عمومی مث 22 سرور ایران اومد، فورواردش کن روی سرور خارجیمون.
برای اینکار بایداز سرور یک به یک استفاده کنیم، داریم به سرور ایرانی میگیم دیتایی که داری رو فوروارد کن.

**Comment by sina1100** [comment]
سلام من ابتدا تشکر از شما که بفکر هستید..من چجوری میتونم vmess تو این دنیای آزاد پیدا کنم میتونید کمکم کنید ؟ ... خودمم نمیدونم چجوری از اینجا سر در اوردم 😅
